services:
  api:
    container_name: worldy-bugle-api
    build:
      context: ./worldy_bugle_api
      dockerfile: Dockerfile
    env_file:
      - worldy_bugle_api/.env
    volumes:
      - ./worldy_bugle_api:/app
    ports:
      - 8005:8005
    depends_on:
      - postgres
    networks:
      - app
    dns:
      - 8.8.8.8
      - 8.8.4.4

  celery:
    container_name: worldy-bugle-celery
    build:
      context: ./worldy_bugle_api
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    env_file:
      - worldy_bugle_api/.env
    volumes:
      - ./worldy_bugle_api:/app
    depends_on:
      - postgres
      - redis

    networks:
      - app
    restart: unless-stopped

  celery-beat:
    container_name: worldy-bugle-celery-beat
    build:
      context: ./worldy_bugle_api
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    env_file:
      - worldy_bugle_api/.env
    volumes:
      - ./worldy_bugle_api:/app
    depends_on:
      - postgres
      - redis
    networks:
      - app
    restart: unless-stopped

  postgres:
    container_name: worldy-bugle-postgres
    image: postgres:latest
    env_file:
      - worldy_bugle_api/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - app

  redis:
    container_name: worldy-bugle-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app

  client:
    container_name: worldy-bugle-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5175:5175
    depends_on:
      - api

networks:
  app:

volumes:
  postgres_data:
    driver: local
