# Generated by Django 5.2.13 on 2026-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='region',
        ),
        migrations.AddField(
            model_name='source',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
