# Generated by Django 5.2.13 on 2026-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='country_code',
        ),
    ]
